name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test

  version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Auto-increment version
        id: semver
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: "v"
          commit-message: "ci: bump version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync version to deno.json
        if: steps.semver.outputs.version
        run: |
          NEW_VERSION=${{ steps.semver.outputs.version }}
          # Update version in deno.json
          jq --arg version "${NEW_VERSION#v}" '.version = $version' deno.json > deno.json.tmp
          mv deno.json.tmp deno.json

          # Commit the change to deno.json
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add deno.json
          git commit -m "ci: sync version to deno.json [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          version: ${{ needs.version.outputs.new_version }}

  publish-deno:
    needs: [test, version]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Publish to Deno Land
        run: npx jsr publish
